"""empty message

Revision ID: 5a684b13c218
Revises: 38bea6df1d15
Create Date: 2025-08-06 18:42:25.481440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a684b13c218'
down_revision = '38bea6df1d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
